/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all per-instance meta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a meta entry (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        key: "name" | "description" | "cdn" | "image" | "defaultGallery" | "defaultTheme" | "defaultLanguage" | "initialGalleryView" | "firstWeekday" | "betaFeatures" | "renditions";
                        value: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one meta entry by key */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: "name" | "description" | "cdn" | "image" | "defaultGallery" | "defaultTheme" | "defaultLanguage" | "initialGalleryView" | "firstWeekday" | "betaFeatures" | "renditions";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Update one meta entry by key (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: "name" | "description" | "cdn" | "image" | "defaultGallery" | "defaultTheme" | "defaultLanguage" | "initialGalleryView" | "firstWeekday" | "betaFeatures" | "renditions";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        value: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete one meta entry by key (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: "name" | "description" | "cdn" | "image" | "defaultGallery" | "defaultTheme" | "defaultLanguage" | "initialGalleryView" | "firstWeekday" | "betaFeatures" | "renditions";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verify token (keep-alive) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Log in, issuing access + refresh tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                            editorGalleries: string[];
                        };
                    };
                };
            };
        };
        /** Log out (revoke this session) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token, issue a new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                            editorGalleries: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tokens/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke all sessions for another user (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            isAdmin: boolean;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a user (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        name?: string;
                        password: string;
                        isAdmin?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a user by id (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        password?: string;
                        isAdmin?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a user by id (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/self/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the caller's own password */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accessToken: string;
                            refreshToken: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List galleries visible to the requester */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": ({
                            id: string;
                            hideMap: boolean;
                        } & {
                            [key: string]: unknown;
                        })[];
                    };
                };
            };
        };
        put?: never;
        /** Create a gallery (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        defaultLanguage?: string;
                        icon?: string;
                        epoch?: string;
                        /** @enum {string} */
                        epochType?: "birthday" | "1-index" | "0-index";
                        /** @enum {string} */
                        theme?: "blue" | "red" | "grayscale" | "contrast" | "alert" | "dark" | "amoled" | "forest" | "silver" | "showcase" | "teal" | "paper" | "amber" | "lavender" | "sage" | "slate" | "midnight" | "espresso";
                        /** @enum {string} */
                        initialView?: "year" | "month" | "day" | "photo";
                        hostname?: string;
                        sources?: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/_order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder galleries (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one gallery (with photos) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            hideMap: boolean;
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Update gallery properties (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        defaultLanguage?: string;
                        icon?: string;
                        epoch?: string;
                        /** @enum {string} */
                        epochType?: "birthday" | "1-index" | "0-index";
                        /** @enum {string} */
                        theme?: "blue" | "red" | "grayscale" | "contrast" | "alert" | "dark" | "amoled" | "forest" | "silver" | "showcase" | "teal" | "paper" | "amber" | "lavender" | "sage" | "slate" | "midnight" | "espresso";
                        /** @enum {string} */
                        initialView?: "year" | "month" | "day" | "photo";
                        hostname?: string;
                        sources?: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a gallery (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set gallery icon from a photo crop (gallery admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sourcePhotoId: string;
                        sourceMaxDim: number;
                        crop: {
                            x: number;
                            y: number;
                            width: number;
                            height: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            icon: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved filters for a gallery */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            sourceGalleryId: string;
                            title: string;
                            description: string;
                            titleLocalized: {
                                [key: string]: string;
                            };
                            descriptionLocalized: {
                                [key: string]: string;
                            };
                            definition: {
                                filter?: {
                                    [key: string]: {
                                        [key: string]: (string | number | boolean | null)[];
                                    };
                                };
                                dateRange?: {
                                    from?: string;
                                    to?: string;
                                };
                                numericRanges?: {
                                    [key: string]: {
                                        min?: number;
                                        max?: number;
                                    };
                                };
                            } & {
                                [key: string]: unknown;
                            };
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a saved filter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        definition: {
                            filter?: {
                                [key: string]: {
                                    [key: string]: (string | number | boolean | null)[];
                                };
                            };
                            dateRange?: {
                                from?: string;
                                to?: string;
                            };
                            numericRanges?: {
                                [key: string]: {
                                    min?: number;
                                    max?: number;
                                };
                            };
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}/filters/{filterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one saved filter by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                    filterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            sourceGalleryId: string;
                            title: string;
                            description: string;
                            titleLocalized: {
                                [key: string]: string;
                            };
                            descriptionLocalized: {
                                [key: string]: string;
                            };
                            definition: {
                                filter?: {
                                    [key: string]: {
                                        [key: string]: (string | number | boolean | null)[];
                                    };
                                };
                                dateRange?: {
                                    from?: string;
                                    to?: string;
                                };
                                numericRanges?: {
                                    [key: string]: {
                                        min?: number;
                                        max?: number;
                                    };
                                };
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        /** Update a saved filter (partial) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                    filterId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        definition?: {
                            filter?: {
                                [key: string]: {
                                    [key: string]: (string | number | boolean | null)[];
                                };
                            };
                            dateRange?: {
                                from?: string;
                                to?: string;
                            };
                            numericRanges?: {
                                [key: string]: {
                                    min?: number;
                                    max?: number;
                                };
                            };
                        } & {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a saved filter */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                    filterId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List photos with optional filters; returns a paginated page of the matching set sorted newest-first by capture timestamp */
        get: {
            parameters: {
                query?: {
                    gallery?: string | string[];
                    orphan?: boolean;
                    dateFrom?: string;
                    dateTo?: string;
                    missing?: ("taken" | "coords" | "place" | "country" | "author" | "title" | "description" | "state-code") | ("taken" | "coords" | "place" | "country" | "author" | "title" | "description" | "state-code")[];
                    duplicates?: boolean;
                    countryMismatch?: boolean;
                    q?: string;
                    page?: number;
                    pageSize?: number;
                    photoIdFocus?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            photos: {
                                [key: string]: unknown;
                            }[];
                            page: number;
                            pageSize: number;
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a photo (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        taken?: {
                            author?: string;
                            location?: {
                                country?: string;
                                place?: string;
                                placeLocalized?: {
                                    [key: string]: string;
                                };
                                coordinates?: {
                                    latitude?: number | null;
                                    longitude?: number | null;
                                    altitude?: number | null;
                                };
                            };
                        };
                        camera?: {
                            make?: string;
                            model?: string;
                        };
                        lens?: {
                            make?: string;
                            model?: string;
                        };
                        exposure?: {
                            focalLength?: number;
                            focalLength35mmEquiv?: number;
                            aperture?: number;
                            exposureTime?: number;
                            iso?: number;
                        };
                        isPrivate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/audit-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit-predicate counts (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            orphan: number;
                            duplicates: number;
                            countryMismatch: number;
                            missing: {
                                taken: number;
                                coords: number;
                                place: number;
                                country: number;
                                author: number;
                                title: number;
                                description: number;
                                "state-code": number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/year-months": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Photo counts grouped by year-month (admin) */
        get: {
            parameters: {
                query?: {
                    gallery?: string | string[];
                    orphan?: boolean;
                    missing?: ("taken" | "coords" | "place" | "country" | "author" | "title" | "description" | "state-code") | ("taken" | "coords" | "place" | "country" | "author" | "title" | "description" | "state-code")[];
                    duplicates?: boolean;
                    countryMismatch?: boolean;
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            buckets: {
                                yearMonth: string;
                                count: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch many photos by id (admin / gallery-editor) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            photos: {
                                [key: string]: unknown;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filter-aware cross-gallery photo list (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        year?: number;
                        month?: number;
                        day?: number;
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one photo by id (gallery-editor on any of the photo's galleries) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Update one photo (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        title?: string;
                        description?: string;
                        titleLocalized?: {
                            [key: string]: string;
                        };
                        descriptionLocalized?: {
                            [key: string]: string;
                        };
                        taken?: {
                            author?: string;
                            location?: {
                                country?: string;
                                place?: string;
                                placeLocalized?: {
                                    [key: string]: string;
                                };
                                coordinates?: {
                                    latitude?: number | null;
                                    longitude?: number | null;
                                    altitude?: number | null;
                                };
                            };
                        };
                        camera?: {
                            make?: string;
                            model?: string;
                        };
                        lens?: {
                            make?: string;
                            model?: string;
                        };
                        exposure?: {
                            focalLength?: number;
                            focalLength35mmEquiv?: number;
                            aperture?: number;
                            exposureTime?: number;
                            iso?: number;
                        };
                        isPrivate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete one photo (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{photoId}/regeocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear and re-fetch geocoded data for one photo (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List photos in a gallery */
        get: {
            parameters: {
                query?: {
                    lang?: string;
                };
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filtered + view-scoped photo fetch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        year?: number;
                        month?: number;
                        day?: number;
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Per-day photo counts (Year heatmap) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        year?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjacent + boundary photos within the filtered set */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        photoId: string;
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            previous?: {
                                [key: string]: unknown;
                            };
                            next?: {
                                [key: string]: unknown;
                            };
                            first?: {
                                [key: string]: unknown;
                            };
                            last?: {
                                [key: string]: unknown;
                            };
                            position?: number;
                            total: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/filter-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filter pill universe (per-category value set) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categoryValues: {
                                [key: string]: string[];
                            };
                            categoryCounts: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byCityLocalized: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/by-original-filename/{originalFilename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a photo by its original camera filename */
        get: {
            parameters: {
                query?: {
                    lang?: string;
                };
                header?: never;
                path: {
                    galleryId: string;
                    originalFilename: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gallery-photos/{galleryId}/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one photo's metadata in a gallery's context */
        get: {
            parameters: {
                query?: {
                    lang?: string;
                };
                header?: never;
                path: {
                    galleryId: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        /** Link a photo to a gallery (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Unlink a photo from a gallery (gallery-editor) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                    photoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user_gallery ACL rows (admin) */
        get: {
            parameters: {
                query?: {
                    userId?: string;
                    galleryId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user_id: string;
                            gallery_id: string;
                            is_editor: number;
                            hide_map: number | null;
                            can_see_private: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user-gallery/{userId}/{galleryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert a user_gallery ACL row (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        isEditor: boolean;
                        hideMap?: boolean | null;
                        canSeePrivate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a user_gallery ACL row (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            description: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create a group (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        id: string;
                        name?: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one group (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            description: string;
                        };
                    };
                };
            };
        };
        /** Update a group (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a group (admin). FK cascade clears memberships and grants. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user ids in a group (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add a user to a group (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove a user from a group (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/group-gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group_gallery ACL rows (admin) */
        get: {
            parameters: {
                query?: {
                    groupId?: string;
                    galleryId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            group_id: string;
                            gallery_id: string;
                            is_editor: number;
                            hide_map: number | null;
                            can_see_private: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/group-gallery/{groupId}/{galleryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert a group_gallery ACL row (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        isEditor: boolean;
                        hideMap?: boolean | null;
                        canSeePrivate?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a group_gallery ACL row (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    groupId: string;
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregated stats for a gallery (gallery view) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            geotaggedCount: number;
                            byCategory: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byYearMonth: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            summary: {
                                first?: string;
                                last?: string;
                                spanDays: number;
                                spanYears: number;
                                spanMonths: number;
                                peakShape: {
                                    [key: string]: string;
                                };
                                variety: {
                                    [key: string]: number;
                                };
                            };
                            daysInYear: {
                                [key: string]: number;
                            };
                            daysInYearMonth: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byStateCountry: {
                                [key: string]: string;
                            };
                            byCityCountry: {
                                [key: string]: string;
                            };
                            byCityLocalized: {
                                [key: string]: string;
                            };
                            categoryValues: {
                                [key: string]: string[];
                            };
                            byGallery: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/galleries/{galleryId}/stats/evolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Per-bucket time-series for a trendable category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    galleryId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category: string;
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            yearMonths: string[];
                            buckets: {
                                [key: string]: {
                                    counts: number[];
                                    cumulative: number[];
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregated stats across all galleries (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            geotaggedCount: number;
                            byCategory: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byYearMonth: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            summary: {
                                first?: string;
                                last?: string;
                                spanDays: number;
                                spanYears: number;
                                spanMonths: number;
                                peakShape: {
                                    [key: string]: string;
                                };
                                variety: {
                                    [key: string]: number;
                                };
                            };
                            daysInYear: {
                                [key: string]: number;
                            };
                            daysInYearMonth: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byStateCountry: {
                                [key: string]: string;
                            };
                            byCityCountry: {
                                [key: string]: string;
                            };
                            byCityLocalized: {
                                [key: string]: string;
                            };
                            categoryValues: {
                                [key: string]: string[];
                            };
                            byGallery: {
                                [key: string]: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/evolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Per-bucket time-series for a trendable category across all galleries (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category: string;
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            yearMonths: string[];
                            buckets: {
                                [key: string]: {
                                    counts: number[];
                                    cumulative: number[];
                                };
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/filter-values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filter pill universe across all galleries (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: {
                            [key: string]: {
                                [key: string]: (string | number | boolean | null)[];
                            };
                        };
                        dateRange?: {
                            from?: string;
                            to?: string;
                        };
                        numericRanges?: {
                            [key: string]: {
                                min?: number;
                                max?: number;
                            };
                        };
                        lang?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categoryValues: {
                                [key: string]: string[];
                            };
                            categoryCounts: {
                                [key: string]: {
                                    [key: string]: number;
                                };
                            };
                            byCityLocalized: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent converter / operator-script activity, pending-queue counts, and recent failures */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recent: {
                                id: number;
                                createdAt: string;
                                photoId: string | null;
                                action: string;
                                status: "success" | "failure" | "skipped";
                                detail: string | null;
                            }[];
                            failures: {
                                id: number;
                                createdAt: string;
                                photoId: string | null;
                                action: string;
                                status: "success" | "failure" | "skipped";
                                detail: string | null;
                            }[];
                            pending: {
                                intake: number;
                                geocode: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
