import React from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";
import styled from "@emotion/styled";
import { Helmet } from "react-helmet-async";
import { useTranslation } from "react-i18next";

import countryData from "i18n-iso-countries";
import countryEn from "i18n-iso-countries/langs/en.json";
import countryFi from "i18n-iso-countries/langs/fi.json";
import countryJa from "i18n-iso-countries/langs/ja.json";

import "./App.css";

import ScrollToPosition from "./components/ScrollToPosition";
import TopMenu from "./components/TopMenu";
import Gallery from "./components/Gallery";

import UserModel, { type User } from "./models/UserModel";

import config from "./lib/config";
import scroll from "./lib/scroll";
import token from "./lib/token";

// JSON-imported locale data — the per-file TS inference gives each a slightly
// different shape (some keys like `CN` are arrays in one and strings in others),
// so type the whole bag as a permissive Record for the registerLocale call.
const countryLocales: Record<string, Parameters<typeof countryData.registerLocale>[0]> = {
  en: countryEn as Parameters<typeof countryData.registerLocale>[0],
  fi: countryFi as Parameters<typeof countryData.registerLocale>[0],
  ja: countryJa as Parameters<typeof countryData.registerLocale>[0],
};

const Footer = styled.div`
  width: 100%;
  text-align: right;
  font-size: x-small;
  margin: 0;
  padding: 0;
  color: var(--inactive-color);
`;

const registerCountryData = (lang: string) => {
  countryData.registerLocale(countryLocales[lang] ?? countryLocales.en);
  return countryData;
};

const App = (): React.ReactElement => {
  const [user, setUser] = React.useState<User | undefined>(undefined);
  const [lang, setLang] = React.useState<string>(config.DEFAULT_LANGUAGE);
  const [activeCountryData, setCountryData] = React.useState(
    registerCountryData(lang)
  );

  const scrollState = scroll();

  const { i18n } = useTranslation();
  i18n.on("languageChanged", (lang: string) => {
    setLang(lang);
    setCountryData(registerCountryData(lang));
  });
  const storedLang = window.localStorage.getItem("lang");
  if (storedLang && storedLang !== lang) {
    i18n.changeLanguage(storedLang);
  } else if (lang !== i18n.language) {
    i18n.changeLanguage(lang);
  }

  if (!user) {
    const storedUserJson = window.localStorage.getItem("user");
    if (storedUserJson) {
      const storedUser = UserModel(JSON.parse(storedUserJson));
      if (storedUser) {
        token.setToken(storedUser.token());
        setUser(storedUser);
      }
    }
  }

  return (
    <>
      <Helmet>
        <title>Photo diary</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="noindex" />
      </Helmet>
      <TopMenu user={user} setUser={setUser} lang={lang} />
      <Router>
        <ScrollToPosition scrollState={scrollState}>
          <Routes>
            <Route
              path="/g/:galleryId/stats"
              element={
                <Gallery
                  user={user}
                  lang={lang}
                  countryData={activeCountryData}
                  isStats={true}
                  scrollState={scrollState}
                />
              }
            />
            <Route
              path="/g/:galleryId/:year/:month/:day/:photoId"
              element={
                <Gallery
                  user={user}
                  lang={lang}
                  countryData={activeCountryData}
                  scrollState={scrollState}
                />
              }
            />
            <Route
              path="/g/:galleryId/:year?/:month?/:day?"
              element={
                <Gallery
                  user={user}
                  lang={lang}
                  countryData={activeCountryData}
                  scrollState={scrollState}
                />
              }
            />
            <Route
              path="/g"
              element={
                <Gallery
                  user={user}
                  lang={lang}
                  countryData={activeCountryData}
                  scrollState={scrollState}
                />
              }
            />
            <Route path="/" element={<Navigate to="/g" replace />} />
          </Routes>
        </ScrollToPosition>
        <Footer>
          Generated by{" "}
          <a href="https://github.com/vlumi/photo-diary">Photo Diary</a> © Ville
          Misaki
        </Footer>
      </Router>
    </>
  );
};
export default App;
