import React from "react";
import {
  BrowserRouter as Router,
  Routes,
  Route,
  Navigate,
} from "react-router-dom";
import styled from "@emotion/styled";
import { useTranslation } from "react-i18next";

import "./App.css";

import ScrollToPosition from "./components/ScrollToPosition";
import TopMenu from "./components/TopMenu";
import Gallery from "./components/Gallery";
import Manage from "./components/Manage";
import ManagePlaceholder from "./components/Manage/Placeholder";
import ManagePhotos from "./components/Manage/Photos";
import ManageGalleryPhotos from "./components/Manage/GalleryPhotos";
import ManagePhotoDrawer from "./components/Manage/PhotoDrawer";
import Notifications from "./components/Notifications";
import LoginModal from "./components/LoginModal";
import ChangePasswordModal from "./components/ChangePasswordModal";

import { useLangStore } from "./stores";

const Footer = styled.div`
  width: 100%;
  text-align: right;
  font-size: x-small;
  margin: 0;
  padding: 0;
  color: var(--inactive-color);
`;

const App = (): React.ReactElement => {
  const { t } = useTranslation();

  // Wait for the country-name dictionary to be loaded before rendering the
  // gallery routes — they pass `countryData` deep into the Stats / Filters
  // subviews and rendering with `undefined` would cause runtime errors. The
  // lang store loads the active language's dictionary at module load.
  const countryDataReady = useLangStore((s) => s.countryData !== undefined);

  return (
    <>
      <title>Photo diary</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="robots" content="noindex" />
      <Notifications />
      <LoginModal />
      <ChangePasswordModal />
      <Router>
        <TopMenu />
        <ScrollToPosition>
          {!countryDataReady ? (
            <div>{t("loading")}</div>
          ) : (
            <Routes>
              <Route
                path="/s/:galleryId"
                element={<Gallery isStats={true} />}
              />
              <Route
                path="/g/:galleryId/:year/:month/:day/:photoId"
                element={<Gallery />}
              />
              <Route
                path="/g/:galleryId/:year?/:month?/:day?"
                element={<Gallery />}
              />
              <Route path="/g" element={<Gallery />} />
              <Route path="/m" element={<Manage />}>
                <Route
                  index
                  element={
                    <ManagePlaceholder
                      titleKey="manage-page-dashboard-title"
                      blurbKey="manage-page-dashboard-blurb"
                    />
                  }
                />
                <Route
                  path="users"
                  element={
                    <ManagePlaceholder
                      titleKey="manage-page-users-title"
                      blurbKey="manage-page-users-blurb"
                    />
                  }
                />
                <Route
                  path="galleries"
                  element={
                    <ManagePlaceholder
                      titleKey="manage-page-galleries-title"
                      blurbKey="manage-page-galleries-blurb"
                    />
                  }
                />
                <Route path="photos" element={<ManagePhotos />}>
                  <Route path=":photoId" element={<ManagePhotoDrawer />} />
                </Route>
                <Route path="g/:galleryId">
                  <Route
                    index
                    element={
                      <ManagePlaceholder
                        titleKey="manage-page-gallery-dashboard-title"
                        blurbKey="manage-page-gallery-dashboard-blurb"
                      />
                    }
                  />
                  <Route path="photos" element={<ManageGalleryPhotos />}>
                    <Route path=":photoId" element={<ManagePhotoDrawer />} />
                  </Route>
                  <Route
                    path="access"
                    element={
                      <ManagePlaceholder
                        titleKey="manage-page-gallery-access-title"
                        blurbKey="manage-page-gallery-access-blurb"
                      />
                    }
                  />
                </Route>
              </Route>
              <Route path="/" element={<Navigate to="/g" replace />} />
            </Routes>
          )}
        </ScrollToPosition>
        <Footer>
          Generated by{" "}
          <a href="https://github.com/vlumi/photo-diary">Photo Diary</a> © Ville
          Misaki
        </Footer>
      </Router>
    </>
  );
};
export default App;
