GET http://localhost:4200/api/sessions
Content-type: application/json
Authorization: Bearer YWRtaW49ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5Ym1GdFpTSTZJbUZrYldsdUlpd2lhV0YwSWpveE5UazBOamd4T0RNemZRLnZPOENtX1I3LTB0WFF4N3pLeXlkN0U1TTRJV3A5Vjc4b2dvR2dUdzNUT1E%3D
