DELETE http://localhost:4200/api/sessions
Content-type: application/json
Cookie: token=YWRtaW49ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5Ym1GdFpTSTZJbUZrYldsdUlpd2lhV0YwSWpveE5UazBOalF3TkRRNGZRLm1IanQtaG9oTUE0VlJGVTRpQl9TeEM5U1hVd3Y0aWpyM09Ec0JRZmhHQW8; Path=/
