POST http://localhost:4200/api/sessions/revoke-all
Content-type: application/json
Cookie: token=cGxhaW5Vc2VyPWV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW5Cc1lXbHVWWE5sY2lJc0ltbGhkQ0k2TVRVNU5EWTRNalF4TUgwLmp2UFphNEFJWjl5ZVVWSkhuams0eTdLaW9qMFlBT2RULVk3b3dnZ3VjNnM%3D; Path=/

{
    "username": "admin",
    "password": ""
}
