GET http://localhost:4200/api/stats
Content-type: application/json
Cookie: token=cGxhaW5Vc2VyPWV5SmhiR2NpT2lKSVV6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUoxYzJWeWJtRnRaU0k2SW5Cc1lXbHVWWE5sY2lJc0ltbGhkQ0k2TVRVNU5EWTRPVEl6T0gwLmlUaXg3OGotTEtpQmxIeVBwZFBFU1o5aE0wTG8xbVNpRHB3WW5laXNGOHM%3D; Path=/
