GET http://localhost:4200/api/users
Content-type: application/json
Authorization: Bearer YWRtaW49ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SjFjMlZ5Ym1GdFpTSTZJbUZrYldsdUlpd2lhV0YwSWpveE5UazBOems0TlRZMmZRLkEtazNxblo4dWEtdklSZnVOaG4yaGQyNTV2YjVnamhXckF0MG5mZEpEZk0=
