// The SQLite driver, assembled from one module per entity. The shared
// connection and schema live in `connection.ts`.
import {
  resolveAccessLevel,
  loadUserGalleryRows,
  upsertUserGallery,
  deleteUserGallery,
  resolveHideMap,
  loadGroups,
  loadGroup,
  createGroup,
  updateGroup,
  deleteGroup,
  loadGroupMembers,
  loadUserGroups,
  addUserGroup,
  removeUserGroup,
  loadGroupGalleryRows,
  upsertGroupGallery,
  deleteGroupGallery,
} from "./access.js";
import {
  _resetForTests,
} from "./connection.js";
import {
  loadGalleries,
  setGalleryOrder,
  createGallery,
  loadGallery,
  updateGallery,
  deleteGallery,
} from "./galleries.js";
import {
  loadGalleryPhotos,
  queryFilteredPhotos,
  queryFilteredPhotosGlobal,
  queryFilteredPhotoCounts,
  queryFilteredPhotoNeighbors,
  queryGalleryFilterValues,
  queryGlobalFilterValues,
  linkGalleryPhoto,
  unlinkGalleryPhoto,
  unlinkAllPhotos,
  unlinkAllGalleries,
  loadAllGalleryPhotoLinks,
  loadGalleryPhoto,
} from "./gallery-photos.js";
import {
  loadMetas,
  createMeta,
  loadMeta,
  updateMeta,
  deleteMeta,
} from "./meta.js";
import {
  logOperation,
  loadRecentOperations,
  loadOperationFailures,
  pruneOperationsBefore,
  consumeSsoJti,
  countPendingGeocode,
} from "./operations.js";
import {
  loadGalleryPhotoByOriginalFilename,
  loadPhotos,
  createPhoto,
  upsertPhotoRendition,
  loadAllPhotoRenditions,
  deletePhotoRendition,
  loadPhoto,
  loadPhotosByOriginalFilename,
  loadOrphanPhotoIds,
  loadOrphanGalleryPhotoLinks,
  loadEmptyGalleryIds,
  loadOrphanUserGalleryRows,
  updatePhoto,
  renamePhoto,
  upsertGeocoded,
  markGeocodeNoData,
  clearGeocoded,
  loadPhotosMissingGeocoded,
  deletePhoto,
  loadPhotoLocalized,
  clearLocalizedCity,
} from "./photos.js";
import {
  loadUsers,
  createUser,
  loadUser,
  updateUser,
  deleteUser,
  createSession,
  loadSession,
  updateSession,
  rotateSessionHash,
  deleteSession,
  deleteUserSessions,
} from "./users.js";
import {
  upsertVirtualGallery,
  deleteVirtualGallery,
  isVirtualGallery,
  isReferencedAsSource,
  loadSavedFilters,
  loadSavedFilter,
  createSavedFilter,
  updateSavedFilter,
  deleteSavedFilter,
} from "./virtual-galleries.js";

export default () => {
  return {
    loadMetas,
    createMeta,
    loadMeta,
    updateMeta,
    deleteMeta,

    loadUsers,
    createUser,
    loadUser,
    updateUser,
    deleteUser,

    createSession,
    loadSession,
    updateSession,
    rotateSessionHash,
    deleteSession,
    deleteUserSessions,

    resolveAccessLevel,
    loadUserGalleryRows,
    upsertUserGallery,
    deleteUserGallery,
    resolveHideMap,

    loadGroups,
    loadGroup,
    createGroup,
    updateGroup,
    deleteGroup,
    loadGroupMembers,
    loadUserGroups,
    addUserGroup,
    removeUserGroup,
    loadGroupGalleryRows,
    upsertGroupGallery,
    deleteGroupGallery,

    loadGalleries,
    setGalleryOrder,
    createGallery,
    loadGallery,
    updateGallery,
    deleteGallery,

    upsertVirtualGallery,
    deleteVirtualGallery,
    isVirtualGallery,
    isReferencedAsSource,

    loadSavedFilters,
    loadSavedFilter,
    createSavedFilter,
    updateSavedFilter,
    deleteSavedFilter,

    loadGalleryPhotos,
    queryFilteredPhotos,
    queryFilteredPhotosGlobal,
    queryFilteredPhotoCounts,
    queryFilteredPhotoNeighbors,
    queryGalleryFilterValues,
    queryGlobalFilterValues,
    linkGalleryPhoto,
    unlinkGalleryPhoto,
    unlinkAllPhotos,
    unlinkAllGalleries,
    loadAllGalleryPhotoLinks,
    loadGalleryPhoto,
    loadGalleryPhotoByOriginalFilename,

    loadPhotos,
    createPhoto,
    upsertPhotoRendition,
    loadAllPhotoRenditions,
    deletePhotoRendition,
    loadPhoto,
    loadPhotosByOriginalFilename,
    loadOrphanPhotoIds,
    loadOrphanGalleryPhotoLinks,
    loadEmptyGalleryIds,
    loadOrphanUserGalleryRows,
    updatePhoto,
    renamePhoto,
    upsertGeocoded,
    markGeocodeNoData,
    clearGeocoded,
    loadPhotosMissingGeocoded,
    deletePhoto,
    loadPhotoLocalized,
    clearLocalizedCity,

    logOperation,
    loadRecentOperations,
    loadOperationFailures,
    pruneOperationsBefore,
    consumeSsoJti,
    countPendingGeocode,

    _resetForTests,
  };
};
